grid_search:
  class: GridSearchCV
  module: sklearn.model_selection
  params:
    cv: 5
    verbose: 2
model_selection:
  module_0:
    class: LinearRegression
    module: sklearn.linear_model
    params:
      fit_intercept: true
    search_param_grid:
      fit_intercept:
      - true
      - false
  module_1:
    class: RandomForestRegressor
    module: sklearn.ensemble
    params:
      n_jobs : -1
      random_state : 42
    search_param_grid:
      max_depth:
      - 8
      - 16
      - 24
      - 32
  module_2:
    class: XGBRegressor
    module: xgboost
    params:
      max_depth : 3
      learning_rate : 0.1
      n_estimators : 100
      objective : "reg:linear"
      n_jobs : -1
      random_state : 42
    search_param_grid:
      n_estimators:
      - 50
      - 100
      - 150
  module_3:
    class: Lasso
    module: sklearn.linear_model
    params:
      alpha: 0.1
    search_param_grid:
      alpha :
      - 0.1
      - 0.25