columns:
  Airline: category
  Date_of_Journey: datetime64[ns]
  Source: category
  Destination: category
  Dep_Time: datetime64[ns]
  Arrival_Time: datetime64[ns]
  Duration: category
  Price: float
  Total_Stops: category

numerical_columns:
  - Date_of_Journey
  - Dep_Time
  - Arrival_Time
  - Duration

categorical_columns:
  - Airline
  - Source
  - Destination
  - Total_Stops

target_column: Price

domain_value:
  Airline:
    - Jet Airways                          
    - IndiGo                               
    - Air India                            
    - Multiple carriers                    
    - SpiceJet                              
    - Vistara                               
    - Air Asia                              
    - GoAir                                 
    - Multiple carriers Premium economy      
    - Jet Airways Business                    
    - Vistara Premium economy                 
    - Trujet    

  Source:
    - Delhi       
    - Kolkata     
    - Banglore    
    - Mumbai       
    - Chennai   

  Destination:
    - Cochin       
    - Banglore     
    - Delhi        
    - New Delhi    
    - Hyderabad    
    - Kolkata   

  Total_Stops:
    - non-stop  
    - 1 stop   
    - 2 stops    
    - 3 stops     
    - 4 stops 


